# Task 2
## Task 2.1
**Deschiderea la dataset**

In [18]:
import pandas as pd
import numpy as np

df = pd.read_csv('wine-quality-white-and-red.csv')

df

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.270,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,white,6.3,0.300,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,white,8.1,0.280,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,red,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
6493,red,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
6494,red,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
6495,red,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
6496,red,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

**Transferarea din string in integer**

In [19]:
count = df['type'].value_counts()

if 'white' in count and 'red' in count:
    df['type'] = df['type'].map({'white': 0, 'red': 1})

count

type
white    4898
red      1599
Name: count, dtype: int64

*Parametrile principale a datasetului*

In [20]:
for axis in range(2):
    print(f'Media{axis+1}', df.mean(axis=axis), sep=' ---> ', end='\n\n')
    print(f'Mediana{axis+1}', df.median(axis=axis), sep=' ---> ', end='\n\n')
    print(f'Modul{axis+1}', df.mode(axis=axis), sep=' ---> ', end='\n\n\n')
    print(f'Std{axis+1}', df.std(axis=axis), sep=' ---> ', end='\n\n\n')

print('\n', df.describe(), sep='')

Media1 ---> type                      0.246114
fixed acidity             7.215307
volatile acidity          0.339666
citric acid               0.318633
residual sugar            5.443235
chlorides                 0.056034
free sulfur dioxide      30.525319
total sulfur dioxide    115.744574
density                   0.994697
pH                        3.218501
sulphates                 0.531268
alcohol                  10.491801
quality                   5.818378
dtype: float64

Mediana1 ---> type                      0.00000
fixed acidity             7.00000
volatile acidity          0.29000
citric acid               0.31000
residual sugar            3.00000
chlorides                 0.04700
free sulfur dioxide      29.00000
total sulfur dioxide    118.00000
density                   0.99489
pH                        3.21000
sulphates                 0.51000
alcohol                  10.30000
quality                   6.00000
dtype: float64

Modul1 --->    type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0   0.0            6.8              0.28          0.3             2.0
1   NaN            NaN               NaN          NaN             NaN

   chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0      0.044                 29.0                 111.0   0.9972  3.16
1        NaN                  NaN                   NaN   0.9976   NaN

   sulphates  alcohol  quality
0        0.5      9.5      6.0
1        NaN      NaN      NaN


Std1 ---> type                     0.430779
fixed acidity            1.296434
volatile acidity         0.164636
citric acid              0.145318
residual sugar           4.757804
chlorides                0.035034
free sulfur dioxide     17.749400
total sulfur dioxide    56.521855
density                  0.002999
pH                       0.160787
sulphates                0.148806
alcohol                  1.192712
quality                  0.873255
dtype: float64


Media2 ---> 0       20.202000
1       13.451769
2       12.578854
3       20.753354
4       20.753354
          ...
6492     8.191915
6493     9.406702
6494     7.806288
6495     8.170421
6496     7.191730
Length: 6497, dtype: float64

Mediana2 ---> 0       3.00
1       1.60
2       3.26
3       3.19
4       3.19
        ...
6492    2.00
6493    2.20
6494    2.30
6495    2.00
6496    3.39
Length: 6497, dtype: float64

Modul2 --->          0      1      2     3        4       5     6     7    8    9     10  \
0     0.000  0.045  0.270  0.36  0.45000  1.0010  3.00  6.00  7.0  8.8  20.7
1     0.000  0.049  0.300  0.34  0.49000  0.9940  1.60  3.30  6.0  6.3   9.5
2     0.000  0.050  0.280  0.40  0.44000  0.9951  3.26  6.00  6.9  8.1  10.1
3     0.000  0.058  0.230  0.32  0.40000  0.9956  3.19  6.00  7.2  8.5   9.9
4     0.000  0.058  0.230  0.32  0.40000  0.9956  3.19  6.00  7.2  8.5   9.9
...     ...    ...    ...   ...      ...     ...   ...   ...  ...  ...   ...
6492  0.080  0.090  0.580  0.60  0.99490  1.0000  2.00  3.45  5.0  6.2  10.5
6493  0.062  0.100  0.550  0.76  0.99512  1.0000  2.20  3.52  5.9  6.0  11.2
6494  0.076  0.130  0.510  0.75  0.99574  1.0000  2.30  3.42  6.0  6.3  11.0
6495  0.075  0.120  0.645  0.71  0.99547  1.0000  2.00  3.57  5.0  5.9  10.2
6496  6.000    NaN    NaN   NaN      NaN     NaN   NaN   NaN  NaN  NaN   NaN

        11     12
0     45.0  170.0
1     14.0  132.0
2     30.0   97.0
3     47.0  186.0
4     47.0  186.0
...    ...    ...
6492  32.0   44.0
6493  39.0   51.0
6494  29.0   40.0
6495  32.0   44.0
6496   NaN    NaN

[6497 rows x 13 columns]


Std2 ---> 0       46.744669
1       35.879979
2       26.638512
3       51.214796
4       51.214796
          ...
6492    13.783734
6493    16.299402
6494    12.467683
6495    13.771047
6496    11.675571
Length: 6497, dtype: float64



              type  fixed acidity  volatile acidity  citric acid  \
count  6497.000000    6497.000000       6497.000000  6497.000000
mean      0.246114       7.215307          0.339666     0.318633
std       0.430779       1.296434          0.164636     0.145318
min       0.000000       3.800000          0.080000     0.000000
25%       0.000000       6.400000          0.230000     0.250000
50%       0.000000       7.000000          0.290000     0.310000
75%       0.000000       7.700000          0.400000     0.390000
max       1.000000      15.900000          1.580000     1.660000

       residual sugar    chlorides  free sulfur dioxide  total sulfur dioxide  \
count     6497.000000  6497.000000          6497.000000           6497.000000
mean         5.443235     0.056034            30.525319            115.744574
std          4.757804     0.035034            17.749400             56.521855
min          0.600000     0.009000             1.000000              6.000000
25%          1.800000     0.038000            17.000000             77.000000
50%          3.000000     0.047000            29.000000            118.000000
75%          8.100000     0.065000            41.000000            156.000000
max         65.800000     0.611000           289.000000            440.000000

           density           pH    sulphates      alcohol      quality
count  6497.000000  6497.000000  6497.000000  6497.000000  6497.000000
mean      0.994697     3.218501     0.531268    10.491801     5.818378
std       0.002999     0.160787     0.148806     1.192712     0.873255
min       0.987110     2.720000     0.220000     8.000000     3.000000
25%       0.992340     3.110000     0.430000     9.500000     5.000000
50%       0.994890     3.210000     0.510000    10.300000     6.000000
75%       0.996990     3.320000     0.600000    11.300000     6.000000
max       1.038980     4.010000     2.000000    14.900000     9.000000

**Gama de valori**

In [21]:
for axis in range(2):
    print(df.max(axis=axis))
    print(df.min(axis=axis))
    print(df.max(axis=axis) - df.min(axis=axis))

type                      1.00000
fixed acidity            15.90000
volatile acidity          1.58000
citric acid               1.66000
residual sugar           65.80000
chlorides                 0.61100
free sulfur dioxide     289.00000
total sulfur dioxide    440.00000
density                   1.03898
pH                        4.01000
sulphates                 2.00000
alcohol                  14.90000
quality                   9.00000
dtype: float64
type                    0.00000
fixed acidity           3.80000
volatile acidity        0.08000
citric acid             0.00000
residual sugar          0.60000
chlorides               0.00900
free sulfur dioxide     1.00000
total sulfur dioxide    6.00000
density                 0.98711
pH                      2.72000
sulphates               0.22000
alcohol                 8.00000
quality                 3.00000
dtype: float64
type                      1.00000
fixed acidity            12.10000
volatile acidity          1.50000
citric acid               1.66000
residual sugar           65.20000
chlorides                 0.60200
free sulfur dioxide     288.00000
total sulfur dioxide    434.00000
density                   0.05187
pH                        1.29000
sulphates                 1.78000
alcohol                   6.90000
quality                   6.00000
dtype: float64
0       170.0
1       132.0
2        97.0
3       186.0
4       186.0
        ...
6492     44.0
6493     51.0
6494     40.0
6495     44.0
6496     42.0
Length: 6497, dtype: float64
0       0.000
1       0.000
2       0.000
3       0.000
4       0.000
        ...
6492    0.080
6493    0.062
6494    0.076
6495    0.075
6496    0.067
Length: 6497, dtype: float64
0       170.000
1       132.000
2        97.000
3       186.000
4       186.000
         ...
6492     43.920
6493     50.938
6494     39.924
6495     43.925
6496     41.933
Length: 6497, dtype: float64

In [22]:
df.diff()

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.0,-0.7,0.030,-0.02,-19.1,0.004,-31.0,-38.0,-0.00700,0.30,0.04,0.7,0.0
2,0.0,1.8,-0.020,0.06,5.3,0.001,16.0,-35.0,0.00110,-0.04,-0.05,0.6,0.0
3,0.0,-0.9,-0.050,-0.08,1.6,0.008,17.0,89.0,0.00050,-0.07,-0.04,-0.2,0.0
4,0.0,0.0,0.000,0.00,0.0,0.000,0.0,0.0,0.00000,0.00,0.00,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,0.0,-0.6,-0.020,0.00,0.1,0.022,4.0,6.0,-0.00161,0.03,-0.24,1.0,-1.0
6493,0.0,-0.3,-0.050,0.02,0.2,-0.028,7.0,7.0,0.00022,0.07,0.18,0.7,1.0
6494,0.0,0.4,-0.040,0.03,0.1,0.014,-10.0,-11.0,0.00062,-0.10,-0.01,-0.2,0.0
6495,0.0,-0.4,0.135,-0.01,-0.3,-0.001,3.0,4.0,-0.00027,0.15,-0.04,-0.8,-1.0
6496,0.0,0.1,-0.335,0.35,1.6,-0.008,-14.0,-2.0,0.00002,-0.18,-0.05,0.8,1.0

## Task 2.2

**Dupa cum am citit in <a href="https://file.notion.so/f/f/afefd9da-628c-4516-b5c2-4e1eff7af20a/e63934aa-6949-4c94-a929-c349fcdade20/Sigmoid_Machine_Learning_Handbook_0_2.pdf?id=bab755b2-8c10-4268-adea-9c3dab9aa95d&table=block&spaceId=afefd9da-628c-4516-b5c2-4e1eff7af20a&expirationTimestamp=1704931200000&signature=sVJzRw-nRlIOO2i5W-YRhipfM6WcQIpyfiPD14oLW7o&downloadName=Sigmoid+Machine+Learning+Handbook_0_2.pdf">cartea precedenta</a>, valoarea la corelatie creste pentru ca valorile din matrice creste ori scade paralel, adica daca creste o valoare, creste si alta/altele. Presupun ca e asa**

In [37]:
def max_correlation(dataframe: pd.DataFrame, column_name: str):
    column_correlation = np.sort(dataframe.corr()[column_name].abs())
    
    return [column_correlation[-c] for c in range(1, 4)]

max_correlation(df,'pH')

[1.0, 0.3298081911317203, 0.32912865072599706]

## Task 2.3

In [35]:
sigma, mu, x = 10, 2, df.values
np.multiply(np.divide(1, np.multiply(sigma, np.sqrt(np.multiply(2, np.pi)))), np.power(np.e, np.multiply(np.divide(-1, 2), np.power(np.divide(np.subtract(x, mu), sigma), 2))))

array([[0.03910427, 0.03520653, 0.03930168, ..., 0.03941787, 0.03165929,
        0.03682701],
       [0.03910427, 0.03637136, 0.0393219 , ..., 0.039442  , 0.03011374,
        0.03682701],
       [0.03910427, 0.03312147, 0.03930846, ..., 0.03941174, 0.02873689,
        0.03682701],
       ...,
       [0.03969525, 0.03637136, 0.03945383, ..., 0.03958377, 0.02660852,
        0.03682701],
       [0.03969525, 0.03697277, 0.03952967, ..., 0.03956367, 0.02850364,
        0.03813878],
       [0.03969525, 0.03682701, 0.03932857, ..., 0.03953766, 0.02660852,
        0.03682701]])

## Task 2.4

In [36]:
x = df.values
np.divide(1, np.add(1, np.power(np.e, -x)))

array([[0.5       , 0.99908895, 0.5670929 , ..., 0.61063923, 0.99984929,
        0.99752738],
       [0.5       , 0.99816706, 0.57444252, ..., 0.62010643, 0.99992515,
        0.99752738],
       [0.5       , 0.99969655, 0.56954622, ..., 0.60825903, 0.99995892,
        0.99752738],
       ...,
       [0.73105858, 0.99816706, 0.62480647, ..., 0.6791787 , 0.9999833 ,
        0.99752738],
       [0.73105858, 0.99726804, 0.65588284, ..., 0.67040116, 0.99996283,
        0.99330715],
       [0.73105858, 0.99752738, 0.57688526, ..., 0.65926039, 0.9999833 ,
        0.99752738]])

## Task 2.5

In [27]:
w = np.random.random(3)
y = np.random.random(6)
y_ = np.random.random(y.__len__())
X = np.random.random((y.__len__(), w.__len__()))
a = 0.0005

update_weights = lambda w, y, y_, X, a: np.subtract(w, np.multiply(a, np.mean(np.multiply(np.subtract(y_, y), X.transpose()).transpose(), axis=0)))

update_weights2 = lambda w, y, y_, X, a: np.subtract(w, np.multiply(a, np.divide(np.dot(X.transpose(), np.subtract(y_, y)), X.__len__())))

print(update_weights1(w, y, y_, X, a))
print(update_weights2(w, y, y_, X, a))

[0.47043122 0.71844849 0.10775867]
[0.47043122 0.71844849 0.10775867]

## Task 2.6

In [28]:
MSE = lambda y, y_: np.divide(np.power(np.sum(y - y_), 2), y.__len__())

MSE(y, y_)

0.22316699371462936

## Task 2.7

In [31]:
loss = lambda y, y_: np.divide(np.sum(np.add(np.multiply(y, np.log(y_)), np.multiply(np.multiply(np.subtract(1, y), np.log(np.subtract(1, y_))), 5))), y.__len__())

loss(y, y_)

-4.890694929633253